spring:
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri:
          https://cognito-idp.us-east-2.amazonaws.com/us-east-2_R894BlMpq
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  exposed:
    generate-ddl: true
jwkURL: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_R894BlMpq/.well-known/jwks.json