spring:
  cloud:
    config:
      enabled: false
  config:
    activate:
      on-profile: dev
    import:
        optional:secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    driverClassName: org.postgresql.Driver
    username: compose-postgres
    password: compose-postgres
  exposed:
    generate-ddl: true
jwkURL: ''