version: '2'
services:
  Expenses-server:
    image: 'expensesapp-server:latest'
    build:
      context: ../../../
    container_name: spring-boot-server
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL_POSTGRES=jdbc:postgresql://expenses_app_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - jwkURL=yourawsurl
      - JWT_ISSUER_URI=yourawsissuer
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:15.1-alpine'
    container_name: expenses_app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"