version: '2'
services:
  app:
    image: 'expensesapp-server:latest'
    build:
      context: ./
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/target/expensesapp-server-0.0.1-SNAPSHOT.jar

  db:
    image: 'postgres:13.1-alpine'
    container_name: expenses_app_postgres_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"